server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${project.datasource.driver-class-name}
      url: jdbc:mysql://${project.datasource.host}:${project.datasource.port}/${project.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${project.datasource.username}
      password: ${project.datasource.password}
  #redis配置
  redis:
    host: ${project.redis.host}
    port: ${project.redis.port}
    database: ${project.redis.database}
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.project.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      project:
        mapper: debug
        service: info
        controller: info

project:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 720000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # user设置jwt签名加密时使用的秘钥
    user-secret-key: ${project.jwt.admin-secret-key}
    # user设置jwt过期时间
    user-ttl: ${project.jwt.admin-ttl}
    # user设置前端传递过来的令牌名称
    user-token-name: ${project.jwt.admin-token-name}
  alioss:
    endpoint: ${project.alioss.endpoint}}
    access-key-id: ${project.alioss.access-key-id}
    access-key-secret: ${project.alioss.access-key-secret}
    bucket-name: ${project.alioss.bucket-name}
  wechat:
    appid: ${project.wechat.appid}
    appsecret: ${project.wechat.appsecret}
    #商城地址
  shop:
    address: ${project.shop.address}
    #百度ak
  baidu:
    ak: ${project.baidu.ak}
